`timescale 1ns/1ps

// PCIe endpoint protocol top level.  The physical interface is packet based;
// electrical PIPE/LTSSM logic can be connected below m/s_phy_axis.
module pcie_endpoint_top
  import tlp_pkg::*;
#(
    parameter int DATA_WIDTH = 32,
    parameter int KEEP_WIDTH = DATA_WIDTH / 8,
    parameter int USER_WIDTH = 3,
    parameter int TAG_COUNT = 32,
    parameter int CONTEXT_WIDTH = 16,
    // Completion Timeout; 0 disables. See tlp_request_tracker.sv header.
    parameter int unsigned CPL_TIMEOUT_CYCLES = 32'd4096,
    parameter int VC_PACKET_DEPTH = 4,
    parameter int BAR_COUNT = 2,
    parameter logic [BAR_COUNT*64-1:0] BAR_BASE = '0,
    parameter logic [BAR_COUNT*64-1:0] BAR_MASK =
        {{(BAR_COUNT-1){64'd0}}, 64'hffff_ffff_ffff_f000},
    parameter logic [BAR_COUNT-1:0] BAR_ENABLE =
        {{(BAR_COUNT-1){1'b0}}, 1'b1},
    parameter int RX_FIFO_SIZE = 3,
    parameter int RETRY_TLP_SIZE = 3,
    parameter int MAX_PAYLOAD_SIZE = 256,
    parameter int REPLAY_TIMER_CYCLES = 16'h0aa0,
    parameter int MAX_REPLAY_ATTEMPTS = 2
) (
    input  logic                     clk_i,
    input  logic                     rst_i,
    input  logic                     phy_link_up_i,
    input  logic                     idle_valid_i,
    input  logic                     transmit_enable_i,

    input  logic [DATA_WIDTH-1:0]    s_phy_axis_tdata,
    input  logic [KEEP_WIDTH-1:0]    s_phy_axis_tkeep,
    input  logic                     s_phy_axis_tvalid,
    input  logic                     s_phy_axis_tlast,
    input  logic [USER_WIDTH-1:0]    s_phy_axis_tuser,
    output logic                     s_phy_axis_tready,
    output logic [DATA_WIDTH-1:0]    m_phy_axis_tdata,
    output logic [KEEP_WIDTH-1:0]    m_phy_axis_tkeep,
    output logic                     m_phy_axis_tvalid,
    output logic                     m_phy_axis_tlast,
    output logic [USER_WIDTH-1:0]    m_phy_axis_tuser,
    input  logic                     m_phy_axis_tready,

    input  logic                     memory_enable_i,
    input  logic                     extended_tag_enable_i,
    input  logic [12:0]              max_payload_bytes_i,
    input  logic [12:0]              max_read_bytes_i,
    input  logic                     rcb_128b_i,

    input  logic                     command_valid_i,
    output logic                     command_ready_o,
    input  tlp_cmd_e                 command_i,
    input  logic [63:0]              command_address_i,
    input  logic [12:0]              command_byte_count_i,
    input  logic [2:0]               command_tc_i,
    input  logic [2:0]               command_attr_i,
    input  logic [2:0]               command_message_route_i,
    input  logic [7:0]               command_message_code_i,
    input  logic [CONTEXT_WIDTH-1:0] command_context_i,
    input  logic                     command_prefix_valid_i,
    input  logic [31:0]              command_prefix_i,
    input  logic                     command_ecrc_enable_i,
    input  logic [DATA_WIDTH-1:0]    command_data_i,
    input  logic [KEEP_WIDTH-1:0]    command_keep_i,
    input  logic                     command_data_valid_i,
    input  logic                     command_data_last_i,
    output logic                     command_data_ready_o,
    output logic                     command_error_valid_o,
    output tlp_error_e               command_error_code_o,

    output logic                     target_request_valid_o,
    input  logic                     target_request_ready_i,
    output tlp_header_t              target_request_header_o,
    output tlp_class_e               target_request_class_o,
    output logic                     target_memory_o,
    output logic                     target_config_o,
    output logic                     target_message_o,
    output logic [2:0]               target_message_route_o,
    output logic [7:0]               target_message_code_o,
    output logic [63:0]              target_message_data_o,
    output logic                     target_config_hit_o,
    output logic                     target_config_type_one_o,
    output logic [11:0]              target_config_offset_o,
    output logic                     target_read_o,
    output logic                     target_write_o,
    output logic                     target_unsupported_o,
    output logic                     target_bar_hit_o,
    output logic                     target_bar_overlap_o,
    output logic [((BAR_COUNT <= 1) ? 1 : $clog2(BAR_COUNT))-1:0] target_bar_o,
    output logic [63:0]              target_offset_o,
    output logic [DATA_WIDTH-1:0]    target_data_o,
    output logic [KEEP_WIDTH-1:0]    target_keep_o,
    output logic                     target_data_valid_o,
    output logic                     target_data_last_o,
    input  logic                     target_data_ready_i,

    input  logic                     completion_request_valid_i,
    output logic                     completion_request_ready_o,
    input  tlp_header_t              completion_request_header_i,
    input  logic [2:0]               completion_request_status_i,
    input  logic [12:0]              completion_request_byte_count_i,
    input  logic [6:0]               completion_request_lower_address_i,
    input  logic                     completion_request_ecrc_enable_i,
    input  logic [DATA_WIDTH-1:0]    completion_request_data_i,
    input  logic [KEEP_WIDTH-1:0]    completion_request_keep_i,
    input  logic                     completion_request_data_valid_i,
    input  logic                     completion_request_data_last_i,
    output logic                     completion_request_data_ready_o,

    output logic                     received_completion_valid_o,
    input  logic                     received_completion_ready_i,
    output tlp_header_t              received_completion_header_o,
    output logic [DATA_WIDTH-1:0]    received_completion_data_o,
    output logic [KEEP_WIDTH-1:0]    received_completion_keep_o,
    output logic                     received_completion_data_valid_o,
    output logic                     received_completion_data_last_o,
    input  logic                     received_completion_data_ready_i,

    output logic                     result_valid_o,
    input  logic                     result_ready_i,
    output logic [CONTEXT_WIDTH-1:0] result_context_o,
    output logic [2:0]               result_status_o,
    output logic                     result_last_o,

    output logic [7:0]               cfg_bus_number_o,
    output logic [4:0]               cfg_device_number_o,
    output logic [2:0]               cfg_function_number_o,
    output logic                     fc_initialized_o,
    output logic                     fc_update_valid_o,
    output logic [7:0]               fc_ph_o,
    output logic [11:0]              fc_pd_o,
    output logic [7:0]               fc_nph_o,
    output logic [11:0]              fc_npd_o,
    output logic [7:0]               fc_cplh_o,
    output logic [11:0]              fc_cpld_o,
    output logic                     malformed_o,
    output logic                     rx_error_valid_o,
    output tlp_error_e               rx_error_code_o,
    output logic                     rx_ecrc_error_o,
    output logic                     tx_error_valid_o,
    output tlp_error_e               tx_error_code_o,
    output logic                     tx_fc_blocked_o,
    output logic                     credit_error_o,
    output logic                     vc_overflow_o,
    output logic                     unexpected_completion_o,
    output tlp_error_e               completion_error_code_o,
    // Completion Timeout sideband. See tlp_request_tracker.sv header.
    output logic                     cpl_timeout_valid_o,
    output logic [7:0]               cpl_timeout_tag_o,
    output logic                     late_cpl_valid_o,
    output logic [7:0]               late_cpl_tag_o,
    output logic [$clog2(TAG_COUNT+1)-1:0] outstanding_o
);

  logic [DATA_WIDTH-1:0] tlp_to_dll_tdata;
  logic [KEEP_WIDTH-1:0] tlp_to_dll_tkeep;
  logic                  tlp_to_dll_tvalid;
  logic                  tlp_to_dll_tlast;
  logic [USER_WIDTH-1:0] tlp_to_dll_tuser;
  logic                  tlp_to_dll_tready;

  logic [DATA_WIDTH-1:0] dll_to_tlp_tdata;
  logic [KEEP_WIDTH-1:0] dll_to_tlp_tkeep;
  logic                  dll_to_tlp_tvalid;
  logic                  dll_to_tlp_tlast;
  logic [USER_WIDTH-1:0] dll_to_tlp_tuser;
  logic                  dll_to_tlp_tready;

  logic [15:0] function_id;

  assign function_id = {
      cfg_bus_number_o, cfg_device_number_o, cfg_function_number_o
  };

  tlp_layer #(
      .DATA_WIDTH(DATA_WIDTH),
      .KEEP_WIDTH(KEEP_WIDTH),
      .USER_WIDTH(USER_WIDTH),
      .TAG_COUNT(TAG_COUNT),
      .CONTEXT_WIDTH(CONTEXT_WIDTH),
      .CPL_TIMEOUT_CYCLES(CPL_TIMEOUT_CYCLES),
      .VC_PACKET_DEPTH(VC_PACKET_DEPTH),
      .PCIE_WIRE_ORDER(1'b1),
      .BAR_COUNT(BAR_COUNT),
      .BAR_BASE(BAR_BASE),
      .BAR_MASK(BAR_MASK),
      .BAR_ENABLE(BAR_ENABLE)
  ) tlp_layer_inst (
      .clk_i(clk_i),
      .rst_i(rst_i),
      .link_up_i(phy_link_up_i),
      .transmit_enable_i(transmit_enable_i),
      .requester_id_i(function_id),
      .completer_id_i(function_id),
      .bus_number_i(cfg_bus_number_o),
      .device_number_i(cfg_device_number_o),
      .function_number_i(cfg_function_number_o),
      .memory_enable_i(memory_enable_i),
      .extended_tag_enable_i(extended_tag_enable_i),
      .max_payload_bytes_i(max_payload_bytes_i),
      .max_read_bytes_i(max_read_bytes_i),
      .rcb_128b_i(rcb_128b_i),
      .fc_initialized_i(fc_initialized_o),
      .fc_update_valid_i(fc_update_valid_o),
      .fc_ph_i(fc_ph_o),
      .fc_pd_i(fc_pd_o),
      .fc_nph_i(fc_nph_o),
      .fc_npd_i(fc_npd_o),
      .fc_cplh_i(fc_cplh_o),
      .fc_cpld_i(fc_cpld_o),
      .s_dllp_axis_tdata(dll_to_tlp_tdata),
      .s_dllp_axis_tkeep(dll_to_tlp_tkeep),
      .s_dllp_axis_tvalid(dll_to_tlp_tvalid),
      .s_dllp_axis_tlast(dll_to_tlp_tlast),
      .s_dllp_axis_tuser(dll_to_tlp_tuser),
      .s_dllp_axis_tready(dll_to_tlp_tready),
      .m_dllp_axis_tdata(tlp_to_dll_tdata),
      .m_dllp_axis_tkeep(tlp_to_dll_tkeep),
      .m_dllp_axis_tvalid(tlp_to_dll_tvalid),
      .m_dllp_axis_tlast(tlp_to_dll_tlast),
      .m_dllp_axis_tuser(tlp_to_dll_tuser),
      .m_dllp_axis_tready(tlp_to_dll_tready),
      .command_valid_i(command_valid_i),
      .command_ready_o(command_ready_o),
      .command_i(command_i),
      .command_address_i(command_address_i),
      .command_byte_count_i(command_byte_count_i),
      .command_tc_i(command_tc_i),
      .command_attr_i(command_attr_i),
      .command_message_route_i(command_message_route_i),
      .command_message_code_i(command_message_code_i),
      .command_context_i(command_context_i),
      .command_prefix_valid_i(command_prefix_valid_i),
      .command_prefix_i(command_prefix_i),
      .command_ecrc_enable_i(command_ecrc_enable_i),
      .command_data_i(command_data_i),
      .command_keep_i(command_keep_i),
      .command_data_valid_i(command_data_valid_i),
      .command_data_last_i(command_data_last_i),
      .command_data_ready_o(command_data_ready_o),
      .command_error_valid_o(command_error_valid_o),
      .command_error_code_o(command_error_code_o),
      // RQ-side tag strobe. Deliberately unused at this top: the tag is
      // consumed by pcie_rq_if on the RC path, not here. Named-empty rather
      // than omitted so PINMISSING stays enabled for real omissions.
      .allocated_tag_o(),
      .allocated_tag_valid_o(),
      .target_request_valid_o(target_request_valid_o),
      .target_request_ready_i(target_request_ready_i),
      .target_request_header_o(target_request_header_o),
      .target_request_class_o(target_request_class_o),
      .target_memory_o(target_memory_o),
      .target_config_o(target_config_o),
      .target_message_o(target_message_o),
      .target_message_route_o(target_message_route_o),
      .target_message_code_o(target_message_code_o),
      .target_message_data_o(target_message_data_o),
      .target_config_hit_o(target_config_hit_o),
      .target_config_type_one_o(target_config_type_one_o),
      .target_config_offset_o(target_config_offset_o),
      .target_read_o(target_read_o),
      .target_write_o(target_write_o),
      .target_unsupported_o(target_unsupported_o),
      .target_bar_hit_o(target_bar_hit_o),
      .target_bar_overlap_o(target_bar_overlap_o),
      .target_bar_o(target_bar_o),
      .target_offset_o(target_offset_o),
      .target_data_o(target_data_o),
      .target_keep_o(target_keep_o),
      .target_data_valid_o(target_data_valid_o),
      .target_data_last_o(target_data_last_o),
      .target_data_ready_i(target_data_ready_i),
      .completion_request_valid_i(completion_request_valid_i),
      .completion_request_ready_o(completion_request_ready_o),
      .completion_request_header_i(completion_request_header_i),
      .completion_request_status_i(completion_request_status_i),
      .completion_request_byte_count_i(completion_request_byte_count_i),
      .completion_request_lower_address_i(completion_request_lower_address_i),
      .completion_request_ecrc_enable_i(completion_request_ecrc_enable_i),
      .completion_request_data_i(completion_request_data_i),
      .completion_request_keep_i(completion_request_keep_i),
      .completion_request_data_valid_i(completion_request_data_valid_i),
      .completion_request_data_last_i(completion_request_data_last_i),
      .completion_request_data_ready_o(completion_request_data_ready_o),
      .received_completion_valid_o(received_completion_valid_o),
      .received_completion_ready_i(received_completion_ready_i),
      .received_completion_header_o(received_completion_header_o),
      .received_completion_data_o(received_completion_data_o),
      .received_completion_keep_o(received_completion_keep_o),
      .received_completion_data_valid_o(received_completion_data_valid_o),
      .received_completion_data_last_o(received_completion_data_last_o),
      .received_completion_data_ready_i(received_completion_data_ready_i),
      .result_valid_o(result_valid_o),
      .result_ready_i(result_ready_i),
      .result_context_o(result_context_o),
      .result_status_o(result_status_o),
      .result_last_o(result_last_o),
      .malformed_o(malformed_o),
      .rx_error_valid_o(rx_error_valid_o),
      .rx_error_code_o(rx_error_code_o),
      .rx_ecrc_error_o(rx_ecrc_error_o),
      .tx_error_valid_o(tx_error_valid_o),
      .tx_error_code_o(tx_error_code_o),
      .tx_fc_blocked_o(tx_fc_blocked_o),
      .credit_error_o(credit_error_o),
      .vc_overflow_o(vc_overflow_o),
      .unexpected_completion_o(unexpected_completion_o),
      .completion_error_code_o(completion_error_code_o),
      .cpl_timeout_valid_o(cpl_timeout_valid_o), .cpl_timeout_tag_o(cpl_timeout_tag_o),
      .late_cpl_valid_o(late_cpl_valid_o), .late_cpl_tag_o(late_cpl_tag_o),
      .outstanding_o(outstanding_o)
  );

  pcie_datalink_layer #(
      .DATA_WIDTH(DATA_WIDTH),
      .STRB_WIDTH(KEEP_WIDTH),
      .KEEP_WIDTH(KEEP_WIDTH),
      .USER_WIDTH(USER_WIDTH),
      .RX_FIFO_SIZE(RX_FIFO_SIZE),
      .RETRY_TLP_SIZE(RETRY_TLP_SIZE),
      .MAX_PAYLOAD_SIZE(MAX_PAYLOAD_SIZE),
      .REPLAY_TIMER_CYCLES(REPLAY_TIMER_CYCLES),
      .MAX_REPLAY_ATTEMPTS(MAX_REPLAY_ATTEMPTS)
  ) datalink_layer_inst (
      .clk_i(clk_i),
      .rst_i(rst_i),
      .s_tlp_axis_tdata(tlp_to_dll_tdata),
      .s_tlp_axis_tkeep(tlp_to_dll_tkeep),
      .s_tlp_axis_tvalid(tlp_to_dll_tvalid),
      .s_tlp_axis_tlast(tlp_to_dll_tlast),
      .s_tlp_axis_tuser(tlp_to_dll_tuser),
      .s_tlp_axis_tready(tlp_to_dll_tready),
      .m_tlp_axis_tdata(dll_to_tlp_tdata),
      .m_tlp_axis_tkeep(dll_to_tlp_tkeep),
      .m_tlp_axis_tvalid(dll_to_tlp_tvalid),
      .m_tlp_axis_tlast(dll_to_tlp_tlast),
      .m_tlp_axis_tuser(dll_to_tlp_tuser),
      .m_tlp_axis_tready(dll_to_tlp_tready),
      .s_phy_axis_tdata(s_phy_axis_tdata),
      .s_phy_axis_tkeep(s_phy_axis_tkeep),
      .s_phy_axis_tvalid(s_phy_axis_tvalid),
      .s_phy_axis_tlast(s_phy_axis_tlast),
      .s_phy_axis_tuser(s_phy_axis_tuser),
      .s_phy_axis_tready(s_phy_axis_tready),
      .m_phy_axis_tdata(m_phy_axis_tdata),
      .m_phy_axis_tkeep(m_phy_axis_tkeep),
      .m_phy_axis_tvalid(m_phy_axis_tvalid),
      .m_phy_axis_tlast(m_phy_axis_tlast),
      .m_phy_axis_tuser(m_phy_axis_tuser),
      .m_phy_axis_tready(m_phy_axis_tready),
      .phy_link_up_i(phy_link_up_i),
      .fc_initialized_o(fc_initialized_o),
      .fc_update_valid_o(fc_update_valid_o),
      .fc_ph_o(fc_ph_o),
      .fc_pd_o(fc_pd_o),
      .fc_nph_o(fc_nph_o),
      .fc_npd_o(fc_npd_o),
      .fc_cplh_o(fc_cplh_o),
      .fc_cpld_o(fc_cpld_o),
      .idle_valid_i(idle_valid_i),
      .cfg_bus_number_o(cfg_bus_number_o),
      .cfg_device_number_o(cfg_device_number_o),
      .cfg_function_number_o(cfg_function_number_o),
      .ext_tag_enable_o(),
      .rcb_128b_o(),
      .max_read_request_size_o(),
      .max_payload_size_o(),
      .msix_enable_o(),
      .msix_mask_o(),
      .status_error_cor_i(rx_error_valid_o || rx_ecrc_error_o),
      .status_error_uncor_i(tx_error_valid_o || malformed_o),
      .rx_cpl_stall_i(!received_completion_ready_i)
  );

endmodule
