# Timing-constraint generator for the integrated Gen1 x1 endpoint OOC flow.
# Gen1 uses the logical PHY's 16-bit PIPE width: 2.5 GT/s / 10 * 16 = 125 MHz.

set CLK_PERIOD_NS        10.000
set PIPE_RX_PERIOD_NS     8.000
set PIPE_TX_PERIOD_NS     8.000
set CLK_UNCERTAINTY_NS    0.100
set INPUT_DELAY_MIN_NS    0.000
set INPUT_DELAY_MAX_NS    2.000
set OUTPUT_DELAY_MIN_NS   0.000
set OUTPUT_DELAY_MAX_NS   2.000

proc write_pcie_ooc_constraints {xdc_path} {
    global CLK_PERIOD_NS PIPE_RX_PERIOD_NS PIPE_TX_PERIOD_NS
    global CLK_UNCERTAINTY_NS
    global INPUT_DELAY_MIN_NS INPUT_DELAY_MAX_NS
    global OUTPUT_DELAY_MIN_NS OUTPUT_DELAY_MAX_NS

    foreach {name value} [list \
        CLK_PERIOD_NS        $CLK_PERIOD_NS \
        PIPE_RX_PERIOD_NS    $PIPE_RX_PERIOD_NS \
        PIPE_TX_PERIOD_NS    $PIPE_TX_PERIOD_NS \
        CLK_UNCERTAINTY_NS   $CLK_UNCERTAINTY_NS \
        INPUT_DELAY_MIN_NS   $INPUT_DELAY_MIN_NS \
        INPUT_DELAY_MAX_NS   $INPUT_DELAY_MAX_NS \
        OUTPUT_DELAY_MIN_NS  $OUTPUT_DELAY_MIN_NS \
        OUTPUT_DELAY_MAX_NS  $OUTPUT_DELAY_MAX_NS] {
        if {![string is double -strict $value]} {
            error "$name must be numeric; got '$value'"
        }
    }

    if {$CLK_PERIOD_NS <= 0.0 || $PIPE_RX_PERIOD_NS <= 0.0 ||
        $PIPE_TX_PERIOD_NS <= 0.0} {
        error "all endpoint clock periods must be greater than zero"
    }
    if {$CLK_UNCERTAINTY_NS < 0.0 ||
        $INPUT_DELAY_MIN_NS < 0.0 || $INPUT_DELAY_MAX_NS < 0.0 ||
        $OUTPUT_DELAY_MIN_NS < 0.0 || $OUTPUT_DELAY_MAX_NS < 0.0} {
        error "clock uncertainty and I/O delays must not be negative"
    }

    file mkdir [file dirname $xdc_path]
    set xdc [open $xdc_path w]

    puts $xdc "# Generated by endpoint_constraints.tcl"
    puts $xdc [format {create_clock -name clk_i -period %s [get_ports clk_i]} \
        $CLK_PERIOD_NS]
    puts $xdc [format {create_clock -name pipe_rx_usr_clk_i -period %s [get_ports pipe_rx_usr_clk_i]} \
        $PIPE_RX_PERIOD_NS]
    puts $xdc [format {create_clock -name pipe_tx_usr_clk_i -period %s [get_ports pipe_tx_usr_clk_i]} \
        $PIPE_TX_PERIOD_NS]

    foreach clock_name {clk_i pipe_rx_usr_clk_i pipe_tx_usr_clk_i} {
        puts $xdc [format {set_clock_uncertainty %s [get_clocks %s]} \
            $CLK_UNCERTAINTY_NS $clock_name]
    }

    puts $xdc {set_clock_groups -asynchronous \
        -group [get_clocks clk_i] \
        -group [get_clocks pipe_rx_usr_clk_i] \
        -group [get_clocks pipe_tx_usr_clk_i]}

    # Packet/application-side signals are synchronous to clk_i.  Compatibility
    # packet ports may be pruned in integrated mode, so every collection is quiet.
    puts $xdc {set endpoint_core_inputs [get_ports -quiet -filter {DIRECTION == IN} {phy_link_up_i idle_valid_i transmit_enable_i s_phy_axis_* m_phy_axis_tready memory_enable_i extended_tag_enable_i max_payload_bytes_i[*] max_read_bytes_i[*] rcb_128b_i command_* target_*_ready_i completion_request_* received_completion_*_ready_i result_ready_i}]}
    puts $xdc [format {set_input_delay -clock [get_clocks clk_i] -min %s $endpoint_core_inputs} \
        $INPUT_DELAY_MIN_NS]
    puts $xdc [format {set_input_delay -clock [get_clocks clk_i] -max %s $endpoint_core_inputs} \
        $INPUT_DELAY_MAX_NS]

    puts $xdc {set endpoint_core_outputs [get_ports -quiet -filter {DIRECTION == OUT} {s_phy_axis_tready m_phy_axis_* command_*_o target_*_o completion_request_*_o received_completion_*_o result_*_o cfg_*_o fc_*_o malformed_o rx_error_* rx_ecrc_error_o tx_error_* tx_fc_blocked_o credit_error_o vc_overflow_o unexpected_completion_o completion_error_code_o cpl_timeout_* late_cpl_* outstanding_o}]}
    puts $xdc [format {set_output_delay -clock [get_clocks clk_i] -min %s $endpoint_core_outputs} \
        $OUTPUT_DELAY_MIN_NS]
    puts $xdc [format {set_output_delay -clock [get_clocks clk_i] -max %s $endpoint_core_outputs} \
        $OUTPUT_DELAY_MAX_NS]

    puts $xdc {set endpoint_rx_inputs [get_ports -quiet -filter {DIRECTION == IN} {phy_rx_symbol_i[*] phy_rx_symbol_valid_i[*] phy_phystatus_i[*] phy_phystatus_rst_i phy_rxelecidle_i[*] phy_rxstatus_i[*]}]}
    puts $xdc [format {set_input_delay -clock [get_clocks pipe_rx_usr_clk_i] -min %s $endpoint_rx_inputs} \
        $INPUT_DELAY_MIN_NS]
    puts $xdc [format {set_input_delay -clock [get_clocks pipe_rx_usr_clk_i] -max %s $endpoint_rx_inputs} \
        $INPUT_DELAY_MAX_NS]

    puts $xdc {set endpoint_tx_outputs [get_ports -quiet -filter {DIRECTION == OUT} {phy_tx_symbol_o[*] phy_tx_symbol_valid_o[*]}]}
    puts $xdc [format {set_output_delay -clock [get_clocks pipe_tx_usr_clk_i] -min %s $endpoint_tx_outputs} \
        $OUTPUT_DELAY_MIN_NS]
    puts $xdc [format {set_output_delay -clock [get_clocks pipe_tx_usr_clk_i] -max %s $endpoint_tx_outputs} \
        $OUTPUT_DELAY_MAX_NS]

    puts $xdc {set endpoint_rx_outputs [get_ports -quiet -filter {DIRECTION == OUT} {phy_txdetectrx_o phy_txelecidle_o[*] phy_txcompliance_o[*] phy_rxpolarity_o[*] phy_powerdown_o[*] phy_rate_o[*] phy_txmargin_o[*] phy_txswing_o phy_txdeemph_o phy_pipe_width_o[*] phy_link_up_o ltssm_state_o[*] phy_rx_code_error_o[*] phy_rx_disparity_error_o[*]}]}
    puts $xdc [format {set_output_delay -clock [get_clocks pipe_rx_usr_clk_i] -min %s $endpoint_rx_outputs} \
        $OUTPUT_DELAY_MIN_NS]
    puts $xdc [format {set_output_delay -clock [get_clocks pipe_rx_usr_clk_i] -max %s $endpoint_rx_outputs} \
        $OUTPUT_DELAY_MAX_NS]

    # rst_i is synchronously consumed in all three domains.  Constrain its
    # deassertion against every clock instead of suppressing reset timing.
    puts $xdc [format {set_input_delay -clock [get_clocks clk_i] -min %s [get_ports rst_i]} \
        $INPUT_DELAY_MIN_NS]
    puts $xdc [format {set_input_delay -clock [get_clocks clk_i] -max %s [get_ports rst_i]} \
        $INPUT_DELAY_MAX_NS]
    puts $xdc [format {set_input_delay -add_delay -clock [get_clocks pipe_rx_usr_clk_i] -min %s [get_ports rst_i]} \
        $INPUT_DELAY_MIN_NS]
    puts $xdc [format {set_input_delay -add_delay -clock [get_clocks pipe_rx_usr_clk_i] -max %s [get_ports rst_i]} \
        $INPUT_DELAY_MAX_NS]
    puts $xdc [format {set_input_delay -add_delay -clock [get_clocks pipe_tx_usr_clk_i] -min %s [get_ports rst_i]} \
        $INPUT_DELAY_MIN_NS]
    puts $xdc [format {set_input_delay -add_delay -clock [get_clocks pipe_tx_usr_clk_i] -max %s [get_ports rst_i]} \
        $INPUT_DELAY_MAX_NS]

    close $xdc
}
