# ---------------------------------------------------------------------------
# Constraint-file generator for the single-clock OOC synthesis units.
#
# This is ordinary Tcl sourced by s1_ooc.tcl. It writes a pure XDC file with
# concrete values so Vivado can load it before timing-driven synthesis.
# ---------------------------------------------------------------------------

# ---- User-editable timing values (nanoseconds) -----------------------------

set CLK_PERIOD_NS       6.500
set CLK_UNCERTAINTY_NS  0.100
set INPUT_DELAY_MIN_NS  0.000
set INPUT_DELAY_MAX_NS  2.752
set OUTPUT_DELAY_MIN_NS 0.000
set OUTPUT_DELAY_MAX_NS 3.000

proc write_pcie_ooc_constraints {xdc_path} {
    global CLK_PERIOD_NS CLK_UNCERTAINTY_NS
    global INPUT_DELAY_MIN_NS INPUT_DELAY_MAX_NS
    global OUTPUT_DELAY_MIN_NS OUTPUT_DELAY_MAX_NS

    foreach {name value} [list \
        CLK_PERIOD_NS       $CLK_PERIOD_NS \
        CLK_UNCERTAINTY_NS  $CLK_UNCERTAINTY_NS \
        INPUT_DELAY_MIN_NS  $INPUT_DELAY_MIN_NS \
        INPUT_DELAY_MAX_NS  $INPUT_DELAY_MAX_NS \
        OUTPUT_DELAY_MIN_NS $OUTPUT_DELAY_MIN_NS \
        OUTPUT_DELAY_MAX_NS $OUTPUT_DELAY_MAX_NS] {
        if {![string is double -strict $value]} {
            error "$name must be numeric; got '$value'"
        }
    }

    if {$CLK_PERIOD_NS <= 0.0} {
        error "CLK_PERIOD_NS must be greater than zero"
    }
    if {$CLK_UNCERTAINTY_NS < 0.0 ||
        $INPUT_DELAY_MIN_NS < 0.0 || $INPUT_DELAY_MAX_NS < 0.0 ||
        $OUTPUT_DELAY_MIN_NS < 0.0 || $OUTPUT_DELAY_MAX_NS < 0.0} {
        error "clock uncertainty and I/O delays must not be negative"
    }

    file mkdir [file dirname $xdc_path]
    set xdc [open $xdc_path w]

    puts $xdc "# Generated by pcie_datalink_layer_constraints.tcl"
    puts $xdc [format {create_clock -name clk_i -period %s [get_ports clk_i]} \
        $CLK_PERIOD_NS]
    puts $xdc [format {set_clock_uncertainty %s [get_clocks clk_i]} \
        $CLK_UNCERTAINTY_NS]

    # rst_i is timed because it drives synchronous reset logic. Only clk_i is
    # excluded from the input-delay collection.
    puts $xdc [format {set_input_delay -clock [get_clocks clk_i] -max %s [get_ports -quiet -filter {DIRECTION == IN && NAME != clk_i}]} \
        $INPUT_DELAY_MAX_NS]
    puts $xdc [format {set_input_delay -clock [get_clocks clk_i] -min %s [get_ports -quiet -filter {DIRECTION == IN && NAME != clk_i}]} \
        $INPUT_DELAY_MIN_NS]

    puts $xdc [format {set_output_delay -clock [get_clocks clk_i] -max %s [get_ports -quiet -filter {DIRECTION == OUT}]} \
        $OUTPUT_DELAY_MAX_NS]
    puts $xdc [format {set_output_delay -clock [get_clocks clk_i] -min %s [get_ports -quiet -filter {DIRECTION == OUT}]} \
        $OUTPUT_DELAY_MIN_NS]

    close $xdc
}
